### ISSUE TITLE
Micro.blog Summary support

### ISSUE THREAD

**Issue by jfmartin67** [ericgregorich/micro-blog-cards-theme#29]
I was wondering if you are aware of the recently introduced support for blog post summaries? Any plans to add support for those? Thanks.

**Comment by ericgregorich** [comment]
@jfmartin67 I pushed an update (v1.9.9) that has summary support on the home page and category pages. Let me know if you see any issues. It looks good to me on my test site.

**Comment by jfmartin67** [comment]
Still not showing up on Micro.blog side.... Github not updated... but thanks!

**Comment by ericgregorich** [comment]
@jfmartin67 It should be coming through soon. I had to approve my own pull request and merge the code. It may also take some time for the update to show up in Micro.blog as Manton only checks for updates maybe once per hour.
